-------------------------------------------------
--https://www.youtube.com/watch?v=ZZebKoySIGI&t=1258s
--LISTAR TODAS LAS BASES DE DATOS DEL SERVIDOR
SELECT * FROM V$DATABASE

--LISTAR TODOS LOS USUARIOS/ESQUEMAS  DENTRO DE LA BASE DE DATOS EN LA CUAL ESTOY CONECTADO
SELECT * FROM DBA_USERS

--CAMBIAR LA FECHA DE EXPIRACI�N DE LA CONTRASE�A
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME 90 --CONTRASE�A CADUCA 
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED
ALTER PROFILE DEFAULT LIMIT PASSWORD_REUSE_TIME 90 PASSWORD_REUSE_MAX UNLIMITED; --EL USUARIO NO PUEDE REUTILIZAR SU CLAVE POR 90 D�AS

--CAMBIAR LA CONTRASE�A DE UN USUARIO/ESQUEMA
ALTER USER SYSTEM IDENTIFIED BY 1234

--DESBLOQUEAR AL USUARIO
ALTER USER SYSTEM ACCOUNT UNLOCK
--CREAR UN USUARIO/ESQUEMA
CREATE USER BLASTERIFY IDENTIFIED BY admin
default tablespace USERS
temporary tablespace TEMP
quota unlimited on USERS

--HABILITAR LOS PRIVILEGISO AL USUARIO
grant create session to BLASTERIFY;
grant create table to BLASTERIFY;
grant create view to BLASTERIFY;
grant create procedure to BLASTERIFY;
grant create trigger to BLASTERIFY;
grant create sequence to BLASTERIFY;
grant create job to BLASTERIFY;

--PERMISOS PARA PODER CREAR USUARIOS/ESQUEMAS
alter session set "_ORACLE_SCRIPT"=true;

-----------------

GRANT ALL PRIVILEGES TO BLASTERIFY;

-------

CREATE USER PankiFood IDENTIFIED BY admin;
GRANT ALL PRIVILEGES TO PankiFood;