//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlasterifyAdmin.UserServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServices.Users_ServicesSoap")]
    public interface Users_ServicesSoap {
        
        // CODEGEN: Generating message contract since element name GetAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        BlasterifyAdmin.UserServices.GetAllResponse GetAll(BlasterifyAdmin.UserServices.GetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        System.Threading.Tasks.Task<BlasterifyAdmin.UserServices.GetAllResponse> GetAllAsync(BlasterifyAdmin.UserServices.GetAllRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAll", Namespace="http://tempuri.org/", Order=0)]
        public BlasterifyAdmin.UserServices.GetAllRequestBody Body;
        
        public GetAllRequest() {
        }
        
        public GetAllRequest(BlasterifyAdmin.UserServices.GetAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllRequestBody {
        
        public GetAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlasterifyAdmin.UserServices.GetAllResponseBody Body;
        
        public GetAllResponse() {
        }
        
        public GetAllResponse(BlasterifyAdmin.UserServices.GetAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllResult;
        
        public GetAllResponseBody() {
        }
        
        public GetAllResponseBody(string GetAllResult) {
            this.GetAllResult = GetAllResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Users_ServicesSoapChannel : BlasterifyAdmin.UserServices.Users_ServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Users_ServicesSoapClient : System.ServiceModel.ClientBase<BlasterifyAdmin.UserServices.Users_ServicesSoap>, BlasterifyAdmin.UserServices.Users_ServicesSoap {
        
        public Users_ServicesSoapClient() {
        }
        
        public Users_ServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Users_ServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Users_ServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Users_ServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlasterifyAdmin.UserServices.GetAllResponse BlasterifyAdmin.UserServices.Users_ServicesSoap.GetAll(BlasterifyAdmin.UserServices.GetAllRequest request) {
            return base.Channel.GetAll(request);
        }
        
        public string GetAll() {
            BlasterifyAdmin.UserServices.GetAllRequest inValue = new BlasterifyAdmin.UserServices.GetAllRequest();
            inValue.Body = new BlasterifyAdmin.UserServices.GetAllRequestBody();
            BlasterifyAdmin.UserServices.GetAllResponse retVal = ((BlasterifyAdmin.UserServices.Users_ServicesSoap)(this)).GetAll(inValue);
            return retVal.Body.GetAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlasterifyAdmin.UserServices.GetAllResponse> BlasterifyAdmin.UserServices.Users_ServicesSoap.GetAllAsync(BlasterifyAdmin.UserServices.GetAllRequest request) {
            return base.Channel.GetAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlasterifyAdmin.UserServices.GetAllResponse> GetAllAsync() {
            BlasterifyAdmin.UserServices.GetAllRequest inValue = new BlasterifyAdmin.UserServices.GetAllRequest();
            inValue.Body = new BlasterifyAdmin.UserServices.GetAllRequestBody();
            return ((BlasterifyAdmin.UserServices.Users_ServicesSoap)(this)).GetAllAsync(inValue);
        }
    }
}
