//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlasterifyAdmin.UserServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServices.UserServicesSoap")]
    public interface UserServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Create(string name, string card_number, string email, string password, int id_subscription, int id_country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CreateAsync(string name, string card_number, string email, string password, int id_subscription, int id_country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserServicesSoapChannel : BlasterifyAdmin.UserServices.UserServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServicesSoapClient : System.ServiceModel.ClientBase<BlasterifyAdmin.UserServices.UserServicesSoap>, BlasterifyAdmin.UserServices.UserServicesSoap {
        
        public UserServicesSoapClient() {
        }
        
        public UserServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Create(string name, string card_number, string email, string password, int id_subscription, int id_country) {
            return base.Channel.Create(name, card_number, email, password, id_subscription, id_country);
        }
        
        public System.Threading.Tasks.Task<bool> CreateAsync(string name, string card_number, string email, string password, int id_subscription, int id_country) {
            return base.Channel.CreateAsync(name, card_number, email, password, id_subscription, id_country);
        }
        
        public string Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<string> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public string GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<string> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
